### PR TITLE
A set of tests for SPARQL Core implementations that ignore SPARQL-SHA…

### PR DESCRIPTION
**Pull request by pfps**
Tests that identify SPARQL Core implementations that completely ignore SPARQL-SHACL constructs
Tests for complex paths with complex validation results
A test with unused ill-formed paths
A test for uniqueLang with other literal for true

### CODE REVIEW

**Comment by HolgerKnublauch** [comment]
Hi Peter, I will wait until Monday or so before merging this as you still seem to be making changes. Ideally, let me know when you're done for good :)

**Comment by pfps** [comment]
Not changes, just additions.

If there is a way to have several outstanding pull requests I will do so but
when I try to pull new stuff, it gets added to the existing pull request.

So please add these.

peter

**Comment by HolgerKnublauch** [comment]
I assume you meant this: https://github.com/w3c/data-shapes/commit/ee4d84103e548ffe1134544e7245077db43e89bd  (Jena parser complained)

**Comment by pfps** [comment]
Yeah.  Thanks,

peter

PS:  SPARQL syntax complexity strikes again.

**Pull request merged**
